DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS saves;

CREATE TABLE users(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL
);

CREATE TABLE saves(
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   savename TEXT NOT NULL,
   user_id INTEGER NOT NULL,
   params TEXT NOT NULL,
   FOREIGN KEY (user_id) REFERENCES users(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
